<!DOCTYPE html>
<html lang="cz">
<head>
<base href="/" />
        <meta charset="UTF-8" />
        <title><?= $titulek ?></title>
        <meta name="description" content="<?= $popis ?>" />
        <meta name="keywords" content="<?= $klicova_slova ?>" /> 
        <link rel="stylesheet" href="style.css" type="text/css"/>
</head>

<body>   
    <header class="header">
        <a href="#" class="logo">Logo</a>

        <nav class="Navbar">
            <a href="#">Úvod</a>
            <a href="#">Kontakty</a>
            <a href="#">Služby</a>
            <a href="#">Šablony</a>
            <a href="#">Objednat</a>
            <a href="#">Obchodní podmínky</a>

        </nav>
    </header>

    <article>
        <?php $this->kontroler->vypisPohled();?>
    </article>
 
</body>
</html>